#!/usr/bin/env python3

import re

file = "/var/log/apache2/access.log"
reqs = []

def parser():
	with open(file, 'r') as log:
		lines = log.readlines()

		for l in lines:
			l = l.strip()
			ip = re.search(r'((?:[1-9]{1,3}\.){3}[1-9]{1,3}).*\.\./\.\./', l)

			if ip:
				req = re.search(r'(GET\s+.*?)\"', l)
				reqs.append(str(ip.group(1)) + " => " + str(req.group(1)))

def write(files, sets):
	with open(files, 'a') as f:
		for line in sets:
			f.write(str(line) + "\n\n")


if __name__ == '__main__':
	parser()
	write("/var/log/apache2/.requests.txt", set(reqs))